spring:
  datasource:
    url: jdbc:mysql://localhost:3307/testDB
    username: root
    password: test123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: test-service

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone:
        http://localhost:8761/eureka

  instance:
    prefer-ip-address: true