eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    server:
      enableSelfPreservation: false

spring:
  application:
    name: discovery-server




server:
  port: 8761